print("Arthimatic Operations")
a=int(input("Enter the frist value : "))
b=int (input("Enter the second value: "))
print("Add = ",a+b)
print("Sub = ",a-b)
print("Mul = ",a*b)
print("Div = ",a/b)
print("Floor Div = ",a//b)
print("Mod(rem div) = ",a%b)
print("Exp = ",a**b)